# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SyslogScan-Daemon-SpamDetector
version:      0.41
version_from: lib/SyslogScan/Daemon/SpamDetector.pm
installdirs:  site
requires:
    Net::Netmask:                  0
    SyslogScan::Daemon:            0
    Tie::Cache::LRU:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
